DROP TABLE IF EXISTS routes;

CREATE TABLE routes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  image TEXT NOT NULL,
  rating TEXT NOT NULL,
  stars TEXT NOT NULL
);
